apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: movies-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 30505
    targetPort: 8080
    protocol: TCP
  selector:
    app: movies-app
    tier: frontend
