apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: movies-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-app
      tier: backend
  template:
    metadata:
      name: backend-pod
      labels:
        app: movies-app
        tier: backend
    spec:
      containers:
      - name: backend
        image: stiliyandr/movies-app-backend:v1.0.1
        envFrom:
        - configMapRef:
            name: backend-cm
        - secretRef:
            name: backend-sec
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
