apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: movies-app
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 5040
    targetPort: 5000
    protocol: TCP
  selector:
    app: movies-app
    tier: backend
